# Exercise Numpy/Scipy

### 1. Basics
1. generate a 1-vector of size 10
2. generate a zero-matrix of size 4x3
3. generate a 3x3 identity matrix
4. generate 100 evenly spaced values between 7 and 9
5. Form the 2-D array (without typing it in explicitly):    
[[1,  6, 11],<br/>
[2,  7, 12],<br/>
[3,  8, 13],<br/>
[4,  9, 14],<br/>
[5, 10, 15]]<br/>
6. contruct a vector of length 100 with alternating ones and zeros ( hint: use slice indexing )
7. construct a 8x8 matrix with a checkboard pattern of zeros and ones
8. compute the inverse, eigenvectors and eigenvalues of the following matrix:
$$\mathbf{A} = \left[\begin{array}
{rrr}
6 & 4 & 9 \\
1 & 0 & 2 \\
3 & 1 & 1
\end{array}\right]
$$


In [7]:
import numpy as np

In [17]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [22]:
np.zeros((4, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [23]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [21]:
np.linspace(7, 9, 100)

array([ 7.        ,  7.02020202,  7.04040404,  7.06060606,  7.08080808,
        7.1010101 ,  7.12121212,  7.14141414,  7.16161616,  7.18181818,
        7.2020202 ,  7.22222222,  7.24242424,  7.26262626,  7.28282828,
        7.3030303 ,  7.32323232,  7.34343434,  7.36363636,  7.38383838,
        7.4040404 ,  7.42424242,  7.44444444,  7.46464646,  7.48484848,
        7.50505051,  7.52525253,  7.54545455,  7.56565657,  7.58585859,
        7.60606061,  7.62626263,  7.64646465,  7.66666667,  7.68686869,
        7.70707071,  7.72727273,  7.74747475,  7.76767677,  7.78787879,
        7.80808081,  7.82828283,  7.84848485,  7.86868687,  7.88888889,
        7.90909091,  7.92929293,  7.94949495,  7.96969697,  7.98989899,
        8.01010101,  8.03030303,  8.05050505,  8.07070707,  8.09090909,
        8.11111111,  8.13131313,  8.15151515,  8.17171717,  8.19191919,
        8.21212121,  8.23232323,  8.25252525,  8.27272727,  8.29292929,
        8.31313131,  8.33333333,  8.35353535,  8.37373737,  8.39

In [ ]:
vec = np.zeros

In [26]:
M = np.zeros ((8, 8))
M[::2, ::2] = 1
M[1::2, 1::2] = 1
M

array([[ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.]])

# 2. Mandelbrot

The mandelbrot set is defined as the set of complex numbers $c$ for which the iteration $z_{n+1} = (z_n)^2 + c$, with $z_0=0$ does not diverge. In this exercise we want to compute the Mandelbrot set within a certain range.

1. implement the function `in_mandelbrot(real, comp)` which computes whether a complex number (real = real part, comp=complex part) belongs to the mandelbrot set. Hint: the complex number 5+3i can be constructed in python as follows: `c = 5 + 1j*3`. Iterate `N_max` times and use the threshold `thresh`.
2. generate a 2D array with `1000x1000` zeros called `M`
3. compute for for all complex numbers with real part between -2 and 1 and with complex part between -1.5 and 1.5 whether they belong the Mandelbrot set and store the result in `M`.


In [1]:
N_max = 50 # number of iterations
thresh = 50 # threshold

def in_mandelbrot(real, comp):
    # computes whether a complex number (real = real part, comp=complex part) belongs to the mandelbrot set
    for i in N_max_:
        return
 
def step(start, step, iterations):
    return (start + (i * step) for i in range(N_max))
 
        for real in step(-2.0, 1))
        for comp in step(-1.5, -1.5))


In [ ]:
# plot the mandelbrot fractal
# assusmes M is a 2D array filled with boolean values
import matplotlib.pyplot as plt
plt.imshow(M)
plt.show()

In [ ]:
M = np.zeros((1000, 1000))